Complete std::numeric_limits for the generic int
NVIDIA/jitify pull request #97
Opened 2022-02-21 13:11 UTC by Robadob

These values almost all refer to floating point properties so just hold sensible defaults, however some code expects them to exist so it's better that they're included.

Values copied from: https://en.cppreference.com/w/cpp/types/numeric_limits

(Another case required to support some [GLM](https://github.com/g-truc/glm/pull/1073) functionality, where `std::numeric_limits<unsigned int>::is_iec559` was being called. Also fixed the remaining values to save finding they're required too later. Left `traps` out, as wasn't 100% sure of the appropriate value.).

2022-02-24 06:34 UTC, benbarsdell requested changes
Thanks for this, just a couple of small changes needed.

2022-02-24 06:34 UTC, benbarsdell commented on jitify.hpp
> +       is_modulo         = false,
`is_modulo` needs to be `true` for unsigned types, and `false` for signed types and bool.

2022-02-24 06:34 UTC, benbarsdell commented on jitify.hpp
> +       // traps             = true // usually true for all except bool, however device code can't trap?
AFAICT device code indeed doesn't trap on /0, so this can be set to false.

2022-02-24 08:25 UTC, Robadob commented on jitify.hpp
> +       is_modulo         = false,
`is_modulo` I had just reused what was already there and not checked, sorted now.

2022-02-24 11:56 UTC, benbarsdell commented on jitify.hpp
> +       is_modulo         = false,
Oops I missed that, thanks for fixing it anyway. I think you can make it `is_modulo = !(is_signed || Max == true /*is bool*/)` to make it `false` for bool too.

2022-02-24 13:49 UTC, Robadob commented on jitify.hpp
> +       is_modulo         = false,
I'm not sure that will work as intended `UINT_MAX==true` evaluates to `true`, because only `0` maps to `false` afaik.
I think `Digits == 1`, should work though.

2022-02-24 13:49 UTC, Robadob commented on jitify.hpp
> +       is_modulo         = false,
or `Max == 1`

2022-02-25 01:09 UTC, benbarsdell commented on jitify.hpp
> +       is_modulo         = false,
The `true` gets promoted to int, not the other way around, but I admit it's confusing and that `Max == 1` is better.

2022-02-25 01:10 UTC, benbarsdell approved these changes

2022-02-25 01:12 UTC, merged